### ISSUE TITLE
log messages off by default

### ISSUE THREAD

**Issue by bpostlethwaite** [kessler/directory-watcher#1]
I required a simple directory watcher with roughly the same basic functionality you have coded on top of fs.watch. Before coding my own I checked npm and found directory-watcher. Yes npm! 
One thing: I am allergic to log messages, they spam my modules stdout, a place for my own app critical information. 
Can we wrap the calls to the logger with if statements that resolve to `true` only if
either:

``` javascript
dwatcher.create('path/to/file', {log: true}, callback)
```

or

``` javascript
dwatcher.create('path/to/file', function (err, watcher) {
 watcher.log = true
})
```

? 
I will happily submit a pull request - it saves me forking and duplicating on npm.

**Comment by kessler** [comment]
Think you can try this (?) :

```
var log4js = require('log4js');
log4js.configure({                
        "appenders": [        
        {
            "type": "logLevelFilter",
            "level": "ERROR",
            appender: {
                "type": "console"
            }
        }]
    });   
```

or maybe level: NONE

If this work, i'll arrange an external api for this like you suggested, to wrap this.
